name: employee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  mailer: ^6.4.1
  mobile_scanner: ^6.0.5
  pretty_qr_code: ^3.3.0
  url_launcher: ^6.2.5


  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.1
  android_intent_plus: ^5.3.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
